- Create and open a new folder
- Rename folder to datasessions
- Go to folder datasessions
- _File_ -> _New terminal_

Terminal Commands

'''sh

git status
git init
git status

'''

- _File_ -> _New Notebook_
- Rename __Untitled.ipynb__ to  __day1.ipynb__

Terminal Commands

'''sh

git status

'''

- _File_ -> _New Text File_
-

# NUMpy Basics

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [4]:
np.info(np.reshape)

 reshape(a, newshape, order='C')

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' options take no account of the me

In [5]:
arr1 =np.array([1,2,3])

In [6]:
arr1

array([1, 2, 3])

In [7]:
dir(arr1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [8]:
arr1.shpae

AttributeError: 'numpy.ndarray' object has no attribute 'shpae'

In [9]:
arr1.size()

3

In [10]:
arr2 = np.arange(1,7). reshape(2,3)

In [11]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 3)

In [14]:
arr2.size

6

In [15]:
arr2.len

AttributeError: 'numpy.ndarray' object has no attribute 'len'

In [16]:
len(arr2)

2

In [17]:
arr2.dtype

dtype('int64')

In [18]:
arr22= np.array([1,2,3.0])

In [19]:
arr22.itemsize

8

In [25]:
temp = np.random.randint(1,30,50)

In [26]:
temp

array([21,  2, 12, 12,  3,  8,  3, 14, 20,  9, 27, 28, 13, 12, 24, 11,  7,
        5, 29, 11,  5, 16, 18, 28, 17, 27, 11, 12, 29,  2, 16,  9,  7, 11,
       16, 29, 12, 18,  5, 22, 19, 12,  6, 15,  5, 28,  4, 25, 24, 15])

temp.mean()

In [27]:
temp.mean()

14.68

In [28]:
temp.max()

29

In [29]:
temp.min()

2

In [30]:
np.median(temp)

12.5

In [31]:
temp.prod()

3948530973297082368

In [32]:
temp.cumsum()

array([ 21,  23,  35,  47,  50,  58,  61,  75,  95, 104, 131, 159, 172,
       184, 208, 219, 226, 231, 260, 271, 276, 292, 310, 338, 355, 382,
       393, 405, 434, 436, 452, 461, 468, 479, 495, 524, 536, 554, 559,
       581, 600, 612, 618, 633, 638, 666, 670, 695, 719, 734])

In [33]:
help(temp.prod)

Help on built-in function prod:

prod(...) method of numpy.ndarray instance
    a.prod(axis=None, dtype=None, out=None, keepdims=False)
    
    Return the product of the array elements over the given axis
    
    Refer to `numpy.prod` for full documentation.
    
    See Also
    --------
    numpy.prod : equivalent function



In [34]:
numpy.prod

NameError: name 'numpy' is not defined

In [35]:
np.info(temp.prod)

a.prod(axis=None, dtype=None, out=None, keepdims=False)

Return the product of the array elements over the given axis

Refer to `numpy.prod` for full documentation.

See Also
--------
numpy.prod : equivalent function


In [36]:
np.__versin__

AttributeError: module 'numpy' has no attribute '__versin__'

In [37]:
np.__version__

'1.16.2'

In [38]:
temp

array([21,  2, 12, 12,  3,  8,  3, 14, 20,  9, 27, 28, 13, 12, 24, 11,  7,
        5, 29, 11,  5, 16, 18, 28, 17, 27, 11, 12, 29,  2, 16,  9,  7, 11,
       16, 29, 12, 18,  5, 22, 19, 12,  6, 15,  5, 28,  4, 25, 24, 15])

In [39]:
temp.cumsum()

array([ 21,  23,  35,  47,  50,  58,  61,  75,  95, 104, 131, 159, 172,
       184, 208, 219, 226, 231, 260, 271, 276, 292, 310, 338, 355, 382,
       393, 405, 434, 436, 452, 461, 468, 479, 495, 524, 536, 554, 559,
       581, 600, 612, 618, 633, 638, 666, 670, 695, 719, 734])

In [40]:
temp.std()

8.235144200316107

In [41]:
temp.sum()

734

In [42]:
temp2=temp.reshape(2,25)

In [43]:
temp2

array([[21,  2, 12, 12,  3,  8,  3, 14, 20,  9, 27, 28, 13, 12, 24, 11,
         7,  5, 29, 11,  5, 16, 18, 28, 17],
       [27, 11, 12, 29,  2, 16,  9,  7, 11, 16, 29, 12, 18,  5, 22, 19,
        12,  6, 15,  5, 28,  4, 25, 24, 15]])

In [44]:
temp2.ndim

2

In [45]:
temp2.min()

2

In [46]:
temp2.max()

29

In [47]:
temp.min()

2

In [48]:
temp2.min()

2

In [49]:
temp.max()

29

In [50]:
temp2.max()

29

In [51]:
temp.std()

8.235144200316107

In [52]:
temp2.std()

8.235144200316107

In [53]:
temp2

array([[21,  2, 12, 12,  3,  8,  3, 14, 20,  9, 27, 28, 13, 12, 24, 11,
         7,  5, 29, 11,  5, 16, 18, 28, 17],
       [27, 11, 12, 29,  2, 16,  9,  7, 11, 16, 29, 12, 18,  5, 22, 19,
        12,  6, 15,  5, 28,  4, 25, 24, 15]])

In [56]:
np.mean(temp2, axis=0)

array([24. ,  6.5, 12. , 20.5,  2.5, 12. ,  6. , 10.5, 15.5, 12.5, 28. ,
       20. , 15.5,  8.5, 23. , 15. ,  9.5,  5.5, 22. ,  8. , 16.5, 10. ,
       21.5, 26. , 16. ])

In [57]:
np.sum(temp2, axis=0)

array([48, 13, 24, 41,  5, 24, 12, 21, 31, 25, 56, 40, 31, 17, 46, 30, 19,
       11, 44, 16, 33, 20, 43, 52, 32])

In [59]:
np.sum(temp2, axis=1)

array([355, 379])

In [60]:
temp3=temp.reshape(2,5,5)

In [61]:
temp3

array([[[21,  2, 12, 12,  3],
        [ 8,  3, 14, 20,  9],
        [27, 28, 13, 12, 24],
        [11,  7,  5, 29, 11],
        [ 5, 16, 18, 28, 17]],

       [[27, 11, 12, 29,  2],
        [16,  9,  7, 11, 16],
        [29, 12, 18,  5, 22],
        [19, 12,  6, 15,  5],
        [28,  4, 25, 24, 15]]])

In [62]:
temp3.shape

(2, 5, 5)

In [63]:
np.sum(temp3)

734

In [64]:
np.sum(temp3, axis=0)

array([[48, 13, 24, 41,  5],
       [24, 12, 21, 31, 25],
       [56, 40, 31, 17, 46],
       [30, 19, 11, 44, 16],
       [33, 20, 43, 52, 32]])

In [66]:
np.sum(temp3, axis=1)

array([[ 72,  56,  62, 101,  64],
       [119,  48,  68,  84,  60]])

In [67]:
np.sum(temp3, axis=2)

array([[ 50,  54, 104,  63,  84],
       [ 81,  59,  86,  57,  96]])

In [68]:
temp4=np.arange(1,17).reshape(2,2,2,2)

In [2]:
temp4

NameError: name 'temp4' is not defined

In [72]:
temp4.sum(axis=0)

array([[[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]])

In [73]:
temp4.sum(axis=1)

array([[[ 6,  8],
        [10, 12]],

       [[22, 24],
        [26, 28]]])

In [74]:
temp4.sum(axis=2)

array([[[ 4,  6],
        [12, 14]],

       [[20, 22],
        [28, 30]]])

In [75]:
temp4.sum(axis=3)

array([[[ 3,  7],
        [11, 15]],

       [[19, 23],
        [27, 31]]])

In [76]:
np.NaN ==np.NaN

False

In [77]:
np.NaN is np.NaN

True

In [78]:
np.Inf == np.Inf

True

In [79]:
np.Infinity == np.Inf

True

In [80]:
np.Inf is np.Inf

True

In [81]:
np.pi

3.141592653589793

In [1]:
temp4

NameError: name 'temp4' is not defined

In [5]:
import numpy as np
temp4= np.arange(1,17).reshape(2,2,2,2)

In [6]:
temp4

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [7]:
temp4.sum(axis=0)

array([[[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]])

In [8]:
temp4

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [9]:
temp4.sum(axis=1)

array([[[ 6,  8],
        [10, 12]],

       [[22, 24],
        [26, 28]]])

In [10]:
temp4.sum(axis=2)

array([[[ 4,  6],
        [12, 14]],

       [[20, 22],
        [28, 30]]])

In [11]:
import datetime

In [12]:
dir('datetime')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [13]:
find()

AttributeError: module 'datetime' has no attribute 'find'