In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

In [4]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

In [19]:
dataset = np.random.randint(1,100,10000)

In [20]:
np.savetxt("sample1.txt",dataset, fmt="%d")

In [32]:
dataset = np.fromfile('sample1.txt', sep="\n", dtype=np.int64)

In [33]:
dataset

array([87, 71,  4, ..., 68, 12, 34])

In [34]:
dataset[0]

87

In [35]:
dataset.size

10000

In [36]:
dataset[:100]

array([87, 71,  4, 33, 23, 79, 97, 19, 25, 10, 41, 49,  4, 13, 93, 26, 89,
       53, 82, 94, 67, 17, 27, 14,  4, 54, 30,  8, 37, 10, 30, 57, 66, 76,
       87, 29, 94, 58, 43, 60, 75, 23,  3, 47, 40, 30, 87, 40, 35, 50, 34,
       23, 83, 25, 67, 33, 14, 78, 48, 91, 35, 82, 44, 39, 31, 88, 91,  2,
        8,  7, 13, 75, 97, 31, 46, 89, 14, 72, 53, 16, 28, 84, 52, 19, 83,
       28, 13, 22, 77, 54,  9, 90,  8,  5, 82, 88,  3, 84, 41, 40])

In [37]:
dataset[-100:]

array([11, 91,  8,  8, 27,  7, 44, 48, 35, 85,  1, 95, 37, 51, 99, 58, 27,
        4, 16, 24, 94, 47, 32, 51,  8, 88, 81,  4, 68, 22, 89,  8, 81, 30,
       69, 83, 63, 61, 38, 11,  5, 19,  1, 47, 76, 41,  2, 36, 20, 81, 60,
       43, 21, 96, 77,  6, 36, 74, 80, 91, 42, 80, 98, 43, 81, 11, 84, 92,
       77, 29, 16, 73, 38, 95, 20, 22, 61, 73,  5, 48, 88, 84, 66, 97, 89,
       42, 42, 53, 57, 55, 49,  5, 73, 45,  7, 46, 44, 68, 12, 34])

In [39]:
dataset[dataset.size - 100:]

array([11, 91,  8,  8, 27,  7, 44, 48, 35, 85,  1, 95, 37, 51, 99, 58, 27,
        4, 16, 24, 94, 47, 32, 51,  8, 88, 81,  4, 68, 22, 89,  8, 81, 30,
       69, 83, 63, 61, 38, 11,  5, 19,  1, 47, 76, 41,  2, 36, 20, 81, 60,
       43, 21, 96, 77,  6, 36, 74, 80, 91, 42, 80, 98, 43, 81, 11, 84, 92,
       77, 29, 16, 73, 38, 95, 20, 22, 61, 73,  5, 48, 88, 84, 66, 97, 89,
       42, 42, 53, 57, 55, 49,  5, 73, 45,  7, 46, 44, 68, 12, 34])

In [40]:
dataset < 10

array([False, False,  True, ..., False, False, False])

In [41]:
dataset[dataset < 10]

array([4, 4, 4, 8, 3, 2, 8, 7, 9, 8, 5, 3, 7, 7, 5, 7, 3, 6, 6, 3, 3, 6,
       2, 7, 1, 8, 7, 9, 9, 1, 4, 7, 6, 2, 4, 7, 3, 8, 4, 3, 6, 7, 4, 9,
       9, 1, 9, 6, 9, 7, 4, 3, 3, 4, 7, 9, 4, 3, 8, 8, 3, 5, 9, 4, 3, 9,
       7, 4, 8, 5, 7, 5, 2, 3, 5, 7, 7, 2, 2, 9, 9, 9, 5, 4, 5, 2, 7, 3,
       1, 7, 3, 6, 3, 8, 6, 3, 1, 2, 8, 4, 7, 4, 9, 4, 3, 9, 3, 7, 5, 4,
       9, 5, 8, 8, 7, 4, 4, 2, 8, 4, 1, 6, 6, 1, 9, 7, 4, 6, 5, 7, 4, 3,
       4, 8, 7, 7, 4, 9, 5, 6, 7, 5, 8, 4, 5, 4, 8, 5, 1, 4, 9, 5, 8, 6,
       6, 2, 4, 4, 8, 6, 7, 5, 2, 2, 3, 6, 9, 6, 8, 2, 7, 4, 8, 1, 5, 5,
       8, 7, 8, 8, 3, 5, 9, 2, 8, 1, 3, 1, 3, 5, 2, 9, 5, 2, 1, 5, 6, 3,
       6, 3, 1, 8, 1, 1, 8, 9, 1, 6, 1, 3, 7, 9, 1, 6, 7, 2, 9, 5, 9, 2,
       4, 7, 3, 2, 4, 4, 3, 5, 7, 7, 3, 6, 7, 4, 6, 8, 8, 5, 4, 2, 6, 5,
       8, 4, 2, 5, 9, 1, 3, 5, 9, 2, 5, 8, 7, 8, 6, 7, 7, 6, 1, 3, 9, 3,
       1, 2, 1, 3, 8, 6, 9, 7, 3, 7, 5, 3, 6, 9, 6, 8, 1, 8, 3, 7, 2, 7,
       9, 5, 4, 7, 6, 3, 4, 2, 5, 7, 5, 9, 6, 7, 6,

In [42]:
dataset[dataset < 3 & dataset > 97]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [43]:
dataset[(dataset < 3) & (dataset > 97)]

array([], dtype=int64)

In [46]:
dataset[(dataset < 3) | (dataset > 97)]

array([ 2, 98,  2,  1, 98, 99,  1,  2, 99, 99,  1, 99, 98, 98, 98,  2,  2,
        2,  2, 98, 99,  1, 99, 98, 99,  1,  2, 99, 99, 98,  2,  1,  1, 99,
       98, 98, 99, 99,  1, 98,  2, 98, 99,  2, 99,  2, 98, 98,  2,  1,  2,
        1, 99,  1, 98,  2, 99,  2,  1, 98, 98, 98,  1, 98,  1,  1,  1,  1,
       99,  1, 99, 98,  2,  2,  2, 98, 99, 98,  2, 98,  2,  1,  2,  1, 98,
        1,  2,  1, 99,  1,  2, 99, 98, 99, 99,  2,  2, 98, 98,  1,  2, 98,
       98, 99,  1, 98, 98,  1, 98,  1,  2,  1, 98, 99, 99,  1, 98,  2,  2,
       99,  2, 98,  1, 99,  2,  1,  1, 99, 98, 98,  1,  2, 99,  2,  1, 98,
        1,  2, 98,  1, 99,  2,  2,  2, 99, 99,  2, 98, 99,  1, 98,  1,  1,
        2,  2, 98,  1,  1, 99, 98, 98, 99, 99, 99, 98,  1, 99,  1,  1,  1,
        1,  2,  2, 99,  1, 99,  2, 99, 99, 99,  1, 98, 99, 99,  1, 98, 98,
       98, 99,  2, 99, 98,  2, 99,  1,  2,  2,  1, 98, 99,  1, 98,  1,  1,
        2, 98, 98, 99,  1, 98,  1, 99, 99, 98, 98, 99,  2, 99, 98,  2,  2,
       99, 99, 99,  2,  1

In [50]:
dset1 =dataset[dataset<3]

In [51]:
dset1

array([2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1,
       2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2,
       1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2,
       2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1,
       2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1,
       2, 2, 1, 2, 1, 2, 1, 1, 2])

In [52]:
dset1.size

163

In [53]:
np.any(dset1)

True

In [54]:
np.all(dset1)

True

In [55]:
np.any(dset1 <2)

True

In [57]:
np.all(dset1 < 2)

False

In [58]:
help(np.where)

Help on built-in function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called whe

In [64]:
np.where(dset1<2)

(array([  2,   3,   5,  10,  11,  14,  15,  16,  21,  23,  24,  27,  28,
         29,  30,  31,  32,  33,  39,  41,  42,  44,  45,  49,  51,  52,
         53,  55,  56,  60,  62,  63,  64,  67,  68,  70,  75,  76,  77,
         80,  81,  82,  83,  84,  85,  86,  89,  91,  92,  95,  98,  99,
        100, 101, 103, 104, 109, 112, 113, 115, 116, 117, 120, 121, 122,
        124, 125, 126, 127, 128, 129, 131, 133, 136, 137, 138, 141, 145,
        148, 150, 152, 153, 156, 158, 160, 161]),)

Return the index

In [62]:
dset1

array([2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1,
       2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2,
       1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2,
       2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1,
       2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1,
       2, 2, 1, 2, 1, 2, 1, 1, 2])

In [65]:
np.where(dset1<2,"ONe","TWO")

array(['TWO', 'TWO', 'ONe', 'ONe', 'TWO', 'ONe', 'TWO', 'TWO', 'TWO',
       'TWO', 'ONe', 'ONe', 'TWO', 'TWO', 'ONe', 'ONe', 'ONe', 'TWO',
       'TWO', 'TWO', 'TWO', 'ONe', 'TWO', 'ONe', 'ONe', 'TWO', 'TWO',
       'ONe', 'ONe', 'ONe', 'ONe', 'ONe', 'ONe', 'ONe', 'TWO', 'TWO',
       'TWO', 'TWO', 'TWO', 'ONe', 'TWO', 'ONe', 'ONe', 'TWO', 'ONe',
       'ONe', 'TWO', 'TWO', 'TWO', 'ONe', 'TWO', 'ONe', 'ONe', 'ONe',
       'TWO', 'ONe', 'ONe', 'TWO', 'TWO', 'TWO', 'ONe', 'TWO', 'ONe',
       'ONe', 'ONe', 'TWO', 'TWO', 'ONe', 'ONe', 'TWO', 'ONe', 'TWO',
       'TWO', 'TWO', 'TWO', 'ONe', 'ONe', 'ONe', 'TWO', 'TWO', 'ONe',
       'ONe', 'ONe', 'ONe', 'ONe', 'ONe', 'ONe', 'TWO', 'TWO', 'ONe',
       'TWO', 'ONe', 'ONe', 'TWO', 'TWO', 'ONe', 'TWO', 'TWO', 'ONe',
       'ONe', 'ONe', 'ONe', 'TWO', 'ONe', 'ONe', 'TWO', 'TWO', 'TWO',
       'TWO', 'ONe', 'TWO', 'TWO', 'ONe', 'ONe', 'TWO', 'ONe', 'ONe',
       'ONe', 'TWO', 'TWO', 'ONe', 'ONe', 'ONe', 'TWO', 'ONe', 'ONe',
       'ONe', 'ONe',

In [66]:
help(np.apply_along_axis)

Help on function apply_along_axis in module numpy:

apply_along_axis(func1d, axis, arr, *args, **kwargs)
    Apply a function to 1-D slices along the given axis.
    
    Execute `func1d(a, *args)` where `func1d` operates on 1-D arrays and `a`
    is a 1-D slice of `arr` along `axis`.
    
    This is equivalent to (but faster than) the following use of `ndindex` and
    `s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                f = func1d(arr[ii + s_[:,] + kk])
                Nj = f.shape
                for jj in ndindex(Nj):
                    out[ii + jj + kk] = f[jj]
    
    Equivalently, eliminating the inner loop, this can be expressed as::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                out[ii + s_[...,] + kk] = func1d(arr[ii + s_[:,] +

In [67]:
def map_nums(val):
    if val==1: return "One"
    elif val==2 : return "Two"
    elif val==3 : return "Three"
    else: return "Other"

In [69]:
dset2=dataset[dataset<5]

In [70]:
dset2

array([4, 4, 4, 3, 2, 3, 3, 3, 3, 2, 1, 1, 4, 2, 4, 3, 4, 3, 4, 1, 4, 3,
       3, 4, 4, 3, 3, 4, 3, 4, 2, 3, 2, 2, 4, 2, 3, 1, 3, 3, 3, 1, 2, 4,
       4, 4, 3, 3, 4, 4, 4, 2, 4, 1, 1, 4, 4, 3, 4, 4, 4, 4, 1, 4, 2, 4,
       4, 2, 2, 3, 2, 4, 1, 3, 2, 1, 3, 1, 3, 2, 2, 1, 3, 3, 1, 1, 1, 1,
       1, 3, 1, 2, 2, 4, 3, 2, 4, 4, 3, 3, 4, 4, 2, 4, 2, 1, 3, 2, 1, 3,
       3, 1, 2, 1, 3, 3, 3, 1, 3, 2, 4, 3, 4, 2, 2, 4, 4, 4, 4, 4, 3, 4,
       1, 3, 4, 2, 4, 4, 1, 1, 3, 4, 1, 2, 1, 4, 3, 4, 1, 3, 4, 2, 3, 2,
       2, 4, 4, 3, 1, 2, 1, 1, 1, 3, 4, 2, 4, 2, 1, 4, 1, 2, 1, 4, 2, 2,
       3, 2, 4, 2, 1, 1, 4, 4, 1, 2, 3, 2, 1, 4, 3, 1, 4, 4, 3, 1, 4, 1,
       1, 4, 4, 4, 1, 1, 2, 2, 3, 1, 2, 1, 4, 1, 4, 4, 2, 4, 3, 4, 2, 1,
       2, 2, 1, 4, 4, 4, 3, 4, 1, 4, 1, 1, 2, 4, 1, 1, 4, 3, 2, 3, 4, 3,
       3, 2, 2, 4, 2, 4, 1, 2, 4, 3, 3, 4, 2, 1, 3, 4, 4, 1, 2, 3, 3, 1,
       4, 4, 3, 3, 3, 1, 3, 1, 3, 3, 4, 4, 2, 3, 2, 4, 1, 1, 1, 3, 2, 1,
       1, 1, 1, 3, 1, 4, 1, 3, 3, 3, 3, 3, 4, 3, 3,

In [71]:
np.apply_along_axis(mapp_nums,0,dset2)

NameError: name 'mapp_nums' is not defined

In [73]:
mapp = np.vectorize (map_nums)

In [74]:
mapp(dset2)

array(['Other', 'Other', 'Other', 'Three', 'Two', 'Three', 'Three',
       'Three', 'Three', 'Two', 'One', 'One', 'Other', 'Two', 'Other',
       'Three', 'Other', 'Three', 'Other', 'One', 'Other', 'Three',
       'Three', 'Other', 'Other', 'Three', 'Three', 'Other', 'Three',
       'Other', 'Two', 'Three', 'Two', 'Two', 'Other', 'Two', 'Three',
       'One', 'Three', 'Three', 'Three', 'One', 'Two', 'Other', 'Other',
       'Other', 'Three', 'Three', 'Other', 'Other', 'Other', 'Two',
       'Other', 'One', 'One', 'Other', 'Other', 'Three', 'Other', 'Other',
       'Other', 'Other', 'One', 'Other', 'Two', 'Other', 'Other', 'Two',
       'Two', 'Three', 'Two', 'Other', 'One', 'Three', 'Two', 'One',
       'Three', 'One', 'Three', 'Two', 'Two', 'One', 'Three', 'Three',
       'One', 'One', 'One', 'One', 'One', 'Three', 'One', 'Two', 'Two',
       'Other', 'Three', 'Two', 'Other', 'Other', 'Three', 'Three',
       'Other', 'Other', 'Two', 'Other', 'Two', 'One', 'Three', 'Two',
       'One'

In [76]:
def m1(arg):
    return arg

In [83]:
def hello(func):
    def wrapper(arg):
        return "Hello "+ func(arg)
    return wrapper

In [84]:
m2 = hello(m1)

In [85]:
m2

<function __main__.hello.<locals>.wrapper(arg)>

In [86]:
m1("world")

'world'

In [87]:
m2("world")

'Hello world'

In [88]:
@hello
def m3(arg):
    return arg*3

In [89]:
m3("world")

'Hello worldworldworld'